### ISSUE TITLE
bug: 无法接收自身消息

### ISSUE THREAD

**Issue by HsiangNianian** [retrofor/iamai#49]
## 无法接收自身消息

开启`gocq`的report-self-message`时每次发送消息会报错。
```
Error handling request
Traceback (most recent call last):
  File "C:\Users\Hsiang_Nianian\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\Hsiang_Nianian\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\iamai\../iamai\iamai\adapter\utils.py", line 230, in handle_reverse_ws_response
    await self.handle_websocket()
  File "D:\iamai\../iamai\iamai\adapter\utils.py", line 251, in handle_websocket
    await self.handle_websocket_msg(msg)
  File "D:\iamai\../iamai\iamai\adapter\cqhttp\__init__.py", line 90, in handle_websocket_msg
    await self.handle_cqhttp_event(msg_dict)
  File "D:\iamai\../iamai\iamai\adapter\cqhttp\__init__.py", line 115, in handle_cqhttp_event
    event_class = get_event_class(post_type, event_type, sub_type)
  File "D:\iamai\../iamai\iamai\adapter\cqhttp\event.py", line 384, in get_event_class
    _cqhttp_events.get(".".join((post_type, event_type, sub_type)))
TypeError: sequence item 1: expected str instance, NoneType found
```

```yml
report-self-message: true
```
![B X97OGCQ V{LD$HGOB~_S](https://user-images.githubusercontent.com/44714368/216026870-4bedef28-31f0-4f4a-9c90-a35db03061f8.png)

尝试定义自身消息事件类型。

_Originally posted by @HsiangNianian in https://github.com/retrofor/iamai/discussions/37_

**Comment by HsiangNianian** [comment]
![image](https://user-images.githubusercontent.com/44714368/218293483-c0ce7134-942e-4cdd-a0cb-40aeb1adcca9.png)
